version: '3.8'

services:
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: username
      POSTGRES_DB: database
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pipeline_empresas_brasil:
    build:
      context: ./pipeline_empresas_brasil
      dockerfile: Dockerfile
    volumes:
      - .:/app
    
volumes:
  db_data: